export const localization = {
  bg: {
    difficulty: "Трудност",
    category: "Категория",
    lives: "Животи",
    nextBtn: "Напред",
    retryBtn: "Повтори същата игра",
    congratz: "Еее, браво!",
    fail: "Ем, кофти, бате :/",
    newGameText: "Нова игра",
    score: "Резултат",
    langSetting: "Избери език",
    themeSettings: "Тема",
    numberOfQuestions: "Брой въпроси",
  },
  en: {
    difficulty: "Difficulty",
    category: "Category",
    lives: "Lives",
    nextBtn: "Next",
    retryBtn: "Repeat same game",
    congratz: "Grant!",
    fail: "Next time :/",
    newGameText: "New game",
    score: "Score",
    langSetting: "Choose language",
    themeSettings: "Theme",
    numberOfQuestions: "Number of questions",
  },
};
