export const localization = {
  bg: {
    gameTitle: "Невъзможната Викторина",
    settingsTitle: "Настройки",
    difficulty: "Трудност",
    category: "Категория",
    lives: "Животи",
    nextBtn: "Напред",
    retryBtn: "Повтори същата игра",
    congratz: "Еее, браво!",
    fail: "Ем, кофти, бате :/",
    newGameText: "Нова игра",
    score: "Резултат",
    langSetting: "Избери език",
    themeSettings: "Тема",
    numberOfQuestions: "Брой въпроси",
    restartQuiz: "Рестартирай Викторината",
    lifeline: "Жокери",
  },
  en: {
    gameTitle: "Impossible Quiz",
    settingsTitle: "Settings",
    difficulty: "Difficulty",
    category: "Category",
    lives: "Lives",
    nextBtn: "Next",
    retryBtn: "Repeat same game",
    congratz: "Congratz!",
    fail: "Next time :/",
    newGameText: "New game",
    score: "Score",
    langSetting: "Choose language",
    themeSettings: "Theme",
    numberOfQuestions: "Number of questions",
    restartQuiz: "Restart Quiz",
    lifeline: "Lifeline",
  },
};
